# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dataworker.v1 import dataworker_pb2 as dataworker_dot_v1_dot_dataworker__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dataworker/v1/dataworker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataWorkerStub(object):
    """外部数据采集服务（akshare 等）；不写入业务库
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/dataworker.v1.DataWorker/HealthCheck',
                request_serializer=dataworker_dot_v1_dot_dataworker__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=dataworker_dot_v1_dot_dataworker__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.FetchQuote = channel.unary_unary(
                '/dataworker.v1.DataWorker/FetchQuote',
                request_serializer=dataworker_dot_v1_dot_dataworker__pb2.FetchQuoteRequest.SerializeToString,
                response_deserializer=dataworker_dot_v1_dot_dataworker__pb2.FetchQuoteResponse.FromString,
                _registered_method=True)
        self.FetchValuation = channel.unary_unary(
                '/dataworker.v1.DataWorker/FetchValuation',
                request_serializer=dataworker_dot_v1_dot_dataworker__pb2.FetchValuationRequest.SerializeToString,
                response_deserializer=dataworker_dot_v1_dot_dataworker__pb2.FetchValuationResponse.FromString,
                _registered_method=True)
        self.FetchAnnouncements = channel.unary_unary(
                '/dataworker.v1.DataWorker/FetchAnnouncements',
                request_serializer=dataworker_dot_v1_dot_dataworker__pb2.FetchAnnouncementsRequest.SerializeToString,
                response_deserializer=dataworker_dot_v1_dot_dataworker__pb2.FetchAnnouncementsResponse.FromString,
                _registered_method=True)
        self.FetchMarketSnapshot = channel.unary_unary(
                '/dataworker.v1.DataWorker/FetchMarketSnapshot',
                request_serializer=dataworker_dot_v1_dot_dataworker__pb2.FetchMarketSnapshotRequest.SerializeToString,
                response_deserializer=dataworker_dot_v1_dot_dataworker__pb2.FetchMarketSnapshotResponse.FromString,
                _registered_method=True)
        self.ExtractDocument = channel.unary_unary(
                '/dataworker.v1.DataWorker/ExtractDocument',
                request_serializer=dataworker_dot_v1_dot_dataworker__pb2.ExtractDocumentRequest.SerializeToString,
                response_deserializer=dataworker_dot_v1_dot_dataworker__pb2.ExtractDocumentResponse.FromString,
                _registered_method=True)


class DataWorkerServicer(object):
    """外部数据采集服务（akshare 等）；不写入业务库
    """

    def HealthCheck(self, request, context):
        """探活；supervisor 启动 worker 后轮询
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchQuote(self, request, context):
        """实时行情；用于 data_snapshot.price_snapshot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchValuation(self, request, context):
        """估值指标；用于建仓 Checklist 辅助（只呈现数据，不下结论）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchAnnouncements(self, request, context):
        """公告/财报日历列表；daily crawl 入口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchMarketSnapshot(self, request, context):
        """指数/市场摘要；data_snapshot.market_snapshot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractDocument(self, request, context):
        """URL/文件/文本抽取；library ingest 预处理
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=dataworker_dot_v1_dot_dataworker__pb2.HealthCheckRequest.FromString,
                    response_serializer=dataworker_dot_v1_dot_dataworker__pb2.HealthCheckResponse.SerializeToString,
            ),
            'FetchQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchQuote,
                    request_deserializer=dataworker_dot_v1_dot_dataworker__pb2.FetchQuoteRequest.FromString,
                    response_serializer=dataworker_dot_v1_dot_dataworker__pb2.FetchQuoteResponse.SerializeToString,
            ),
            'FetchValuation': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchValuation,
                    request_deserializer=dataworker_dot_v1_dot_dataworker__pb2.FetchValuationRequest.FromString,
                    response_serializer=dataworker_dot_v1_dot_dataworker__pb2.FetchValuationResponse.SerializeToString,
            ),
            'FetchAnnouncements': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchAnnouncements,
                    request_deserializer=dataworker_dot_v1_dot_dataworker__pb2.FetchAnnouncementsRequest.FromString,
                    response_serializer=dataworker_dot_v1_dot_dataworker__pb2.FetchAnnouncementsResponse.SerializeToString,
            ),
            'FetchMarketSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchMarketSnapshot,
                    request_deserializer=dataworker_dot_v1_dot_dataworker__pb2.FetchMarketSnapshotRequest.FromString,
                    response_serializer=dataworker_dot_v1_dot_dataworker__pb2.FetchMarketSnapshotResponse.SerializeToString,
            ),
            'ExtractDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractDocument,
                    request_deserializer=dataworker_dot_v1_dot_dataworker__pb2.ExtractDocumentRequest.FromString,
                    response_serializer=dataworker_dot_v1_dot_dataworker__pb2.ExtractDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataworker.v1.DataWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataworker.v1.DataWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataWorker(object):
    """外部数据采集服务（akshare 等）；不写入业务库
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataworker.v1.DataWorker/HealthCheck',
            dataworker_dot_v1_dot_dataworker__pb2.HealthCheckRequest.SerializeToString,
            dataworker_dot_v1_dot_dataworker__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataworker.v1.DataWorker/FetchQuote',
            dataworker_dot_v1_dot_dataworker__pb2.FetchQuoteRequest.SerializeToString,
            dataworker_dot_v1_dot_dataworker__pb2.FetchQuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchValuation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataworker.v1.DataWorker/FetchValuation',
            dataworker_dot_v1_dot_dataworker__pb2.FetchValuationRequest.SerializeToString,
            dataworker_dot_v1_dot_dataworker__pb2.FetchValuationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchAnnouncements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataworker.v1.DataWorker/FetchAnnouncements',
            dataworker_dot_v1_dot_dataworker__pb2.FetchAnnouncementsRequest.SerializeToString,
            dataworker_dot_v1_dot_dataworker__pb2.FetchAnnouncementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchMarketSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataworker.v1.DataWorker/FetchMarketSnapshot',
            dataworker_dot_v1_dot_dataworker__pb2.FetchMarketSnapshotRequest.SerializeToString,
            dataworker_dot_v1_dot_dataworker__pb2.FetchMarketSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataworker.v1.DataWorker/ExtractDocument',
            dataworker_dot_v1_dot_dataworker__pb2.ExtractDocumentRequest.SerializeToString,
            dataworker_dot_v1_dot_dataworker__pb2.ExtractDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
